M48
; DRILL file {KiCad 6.0.11+dfsg-1} date Sat Nov 18 19:10:18 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-18T19:10:18+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1063
%
G90
G05
T1
X3.1213Y-4.2024
X3.1213Y-4.4299
T2
X4.6358Y-3.4626
X4.6358Y-3.7768
T3
X2.9921Y-4.0059
X3.6417Y-3.0709
X4.7236Y-4.8023
T0
M30
